swagger: '2.0'
info:
  version: 1.0.0
  title: Blob Hub Service API
  description: API for handling blob query in the Blob Hub.
host: 'blob-hub'
#basePath: "/eth/v1"
schemes:
  - http

paths:
  /eth/v1/beacon/blob_sidecars/{block_id}:
    get:
      tags:
        - "blob"
      summary: "Get blob sidecars by block num"
      operationId: "getBlobSidecarsByBlockNum"
      produces:
        - "application/json"
      parameters:
        - name: "block_id"
          in: "path"
          description: "Block identifier. Can be one of: 'head' (canonical head in node's view), 'genesis', 'finalized', <slot>, <hex encoded blockRoot with 0x prefix>"
          required: true
          type: string
          minLength: 1
        - name: "indices"
          in: "query"
          description: "Array of indices for blob sidecars to request for in the specified block. Returns all blob sidecars in the block if not specified"
          type: array
          items:
            type: string
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetBlobSideCarsResponse"
        "400":
          description: 'Bad Request'
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: 'blob not found'
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: 'internal server error'
          schema:
            $ref: "#/definitions/Error"

  /:
    post:
      tags:
        - "blob"
      summary: "Get BSC blob sidecars by block num"
      operationId: "getBSCBlobSidecarsByBlockNum"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/RPCRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/RPCResponse"
        "500":
          description: 'internal server error'
          schema:
            $ref: "#/definitions/Error"

definitions:
  GetBlobSideCarsResponse:
    type: object
    properties:
      code:
        type: integer
        description: "status code"
        example: 200
      message:
        type: string
        description: "error message if there is error"
        example: "signature invalid"
      data:
        description: "actual data for request"
        type: array
        items:
          $ref: "#/definitions/Sidecar"
  Sidecar:
    type: object
    properties:
      index:
        type: string
        example: 1
      blob:
        type: string
      kzg_commitment:
        type: string
      kzg_proof:
        type: string
      kzg_commitment_inclusion_proof:
        type: array
        x-omitempty: true
        items:
          type: string
      signed_block_header:
        type: object
        properties:
          signature:
            type: string
          message:
            type: object
            properties:
              slot:
                type: string
              proposer_index:
                type: string
              parent_root:
                type: string
              state_root:
                type: string
              body_root:
                type: string
      tx_index:
        type: integer
        format: int64
        x-omitempty: true
      tx_hash:
        type: string

  RPCRequest:
    type: object
    properties:
      jsonrpc:
        type: string
        example: "2.0"
      method:
        type: string
        example: "eth_getBlobSidecars"
      params:
        type: array
        items:
          type: string
        example: ["0x1", true]
      id:
        type: integer
        example: 1

  RPCResponse:
    type: object
    properties:
      jsonrpc:
        type: string
        example: "2.0"
      result:
        type: array
        items:
          $ref: "#/definitions/BSCBlobTxSidecar"
      id:
        type: integer
        example: 1
      error:
        $ref: "#/definitions/RPCError"


  BSCBlobSidecar:
    type: object
    properties:
      blobs:
        type: array
        items:
          type: string
      commitments:
        type: array
        items:
          type: string
      proofs:
        type: array
        items:
          type: "string"

  BSCBlobTxSidecar:
    type: object
    properties:
      blobSidecar:
        $ref: "#/definitions/BSCBlobSidecar"
      blockNumber:
        type: string
      blockHash:
        type: string
      txIndex:
        type: string
      txHash:
        type: string

  RPCError:
    type: object
    properties:
      code:
        x-omitempty: false
        type: integer
        format: int64
        description: "RPC error code"
        example: -32602
      message:
        x-omitempty: false
        type: string
        description: "Error message"
        example: "Invalid params"

  Error:
    type: object
    properties:
      code:
        x-omitempty: false
        type: integer
        format: int64
        description: "HTTP error code"
        example: "400/500"
      message:
        x-omitempty: false
        type: string
        description: "Error message"
        example: "Bad request/Internal server error"
