// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Blob Hub Service API
//
//	API for handling blob query in the Blob Hub.
//	Schemes:
//	  http
//	Host: blob-hub
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
