// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Blob Syncer Service API
//
//	API for handling blob query in the Blob Syncer.
//	Schemes:
//	  http
//	Host: blob-syncer
//	BasePath: /eth/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
