// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for handling blob query in the Blob Syncer.",
    "title": "Blob Syncer Service API",
    "version": "1.0.0"
  },
  "host": "blob-syncer",
  "basePath": "/eth/v1",
  "paths": {
    "/beacon/blob_sidecars/{blockNum}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "blob"
        ],
        "summary": "Get blob sidecars by block num",
        "operationId": "getBlobSidecarsByBlockNum",
        "parameters": [
          {
            "minLength": 1,
            "type": "integer",
            "format": "int64",
            "description": "blockNum",
            "name": "blockNum",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/GetBlobSideCarsResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "description": "HTTP error code",
          "type": "integer",
          "format": "int64",
          "x-omitempty": false,
          "example": "400/500"
        },
        "message": {
          "description": "Error message",
          "type": "string",
          "x-omitempty": false,
          "example": "Bad request/Internal server error"
        }
      }
    },
    "GetBlobSideCarsResponse": {
      "type": "object",
      "properties": {
        "code": {
          "description": "code defined by api,not equal to http code",
          "type": "integer",
          "example": 2000
        },
        "data": {
          "description": "actual data for request",
          "type": "object",
          "properties": {
            "sidecar": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Sidecar"
              }
            }
          }
        },
        "message": {
          "description": "error message if there is error",
          "type": "string",
          "example": "signature invalid"
        }
      }
    },
    "Sidecar": {
      "type": "object",
      "properties": {
        "blob": {
          "description": "name",
          "type": "string",
          "example": "Art"
        },
        "index": {
          "description": "index",
          "type": "integer",
          "format": "int",
          "example": 1
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for handling blob query in the Blob Syncer.",
    "title": "Blob Syncer Service API",
    "version": "1.0.0"
  },
  "host": "blob-syncer",
  "basePath": "/eth/v1",
  "paths": {
    "/beacon/blob_sidecars/{blockNum}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "blob"
        ],
        "summary": "Get blob sidecars by block num",
        "operationId": "getBlobSidecarsByBlockNum",
        "parameters": [
          {
            "minLength": 1,
            "type": "integer",
            "format": "int64",
            "description": "blockNum",
            "name": "blockNum",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/GetBlobSideCarsResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "description": "HTTP error code",
          "type": "integer",
          "format": "int64",
          "x-omitempty": false,
          "example": "400/500"
        },
        "message": {
          "description": "Error message",
          "type": "string",
          "x-omitempty": false,
          "example": "Bad request/Internal server error"
        }
      }
    },
    "GetBlobSideCarsResponse": {
      "type": "object",
      "properties": {
        "code": {
          "description": "code defined by api,not equal to http code",
          "type": "integer",
          "example": 2000
        },
        "data": {
          "description": "actual data for request",
          "type": "object",
          "properties": {
            "sidecar": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Sidecar"
              }
            }
          }
        },
        "message": {
          "description": "error message if there is error",
          "type": "string",
          "example": "signature invalid"
        }
      }
    },
    "GetBlobSideCarsResponseData": {
      "description": "actual data for request",
      "type": "object",
      "properties": {
        "sidecar": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Sidecar"
          }
        }
      }
    },
    "Sidecar": {
      "type": "object",
      "properties": {
        "blob": {
          "description": "name",
          "type": "string",
          "example": "Art"
        },
        "index": {
          "description": "index",
          "type": "integer",
          "format": "int",
          "example": 1
        }
      }
    }
  }
}`))
}
