// Code generated by go-swagger; DO NOT EDIT.

package blob

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bnb-chain/blob-hub/models"
)

// GetBSCBlobSidecarsByBlockNumOKCode is the HTTP code returned for type GetBSCBlobSidecarsByBlockNumOK
const GetBSCBlobSidecarsByBlockNumOKCode int = 200

/*
GetBSCBlobSidecarsByBlockNumOK successful operation

swagger:response getBSCBlobSidecarsByBlockNumOK
*/
type GetBSCBlobSidecarsByBlockNumOK struct {

	/*
	  In: Body
	*/
	Payload *models.RPCResponse `json:"body,omitempty"`
}

// NewGetBSCBlobSidecarsByBlockNumOK creates GetBSCBlobSidecarsByBlockNumOK with default headers values
func NewGetBSCBlobSidecarsByBlockNumOK() *GetBSCBlobSidecarsByBlockNumOK {

	return &GetBSCBlobSidecarsByBlockNumOK{}
}

// WithPayload adds the payload to the get b s c blob sidecars by block num o k response
func (o *GetBSCBlobSidecarsByBlockNumOK) WithPayload(payload *models.RPCResponse) *GetBSCBlobSidecarsByBlockNumOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get b s c blob sidecars by block num o k response
func (o *GetBSCBlobSidecarsByBlockNumOK) SetPayload(payload *models.RPCResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBSCBlobSidecarsByBlockNumOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBSCBlobSidecarsByBlockNumInternalServerErrorCode is the HTTP code returned for type GetBSCBlobSidecarsByBlockNumInternalServerError
const GetBSCBlobSidecarsByBlockNumInternalServerErrorCode int = 500

/*
GetBSCBlobSidecarsByBlockNumInternalServerError internal server error

swagger:response getBSCBlobSidecarsByBlockNumInternalServerError
*/
type GetBSCBlobSidecarsByBlockNumInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBSCBlobSidecarsByBlockNumInternalServerError creates GetBSCBlobSidecarsByBlockNumInternalServerError with default headers values
func NewGetBSCBlobSidecarsByBlockNumInternalServerError() *GetBSCBlobSidecarsByBlockNumInternalServerError {

	return &GetBSCBlobSidecarsByBlockNumInternalServerError{}
}

// WithPayload adds the payload to the get b s c blob sidecars by block num internal server error response
func (o *GetBSCBlobSidecarsByBlockNumInternalServerError) WithPayload(payload *models.Error) *GetBSCBlobSidecarsByBlockNumInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get b s c blob sidecars by block num internal server error response
func (o *GetBSCBlobSidecarsByBlockNumInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBSCBlobSidecarsByBlockNumInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
