// Code generated by go-swagger; DO NOT EDIT.

package blob

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBSCBlobSidecarsByBlockNumHandlerFunc turns a function with the right signature into a get b s c blob sidecars by block num handler
type GetBSCBlobSidecarsByBlockNumHandlerFunc func(GetBSCBlobSidecarsByBlockNumParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBSCBlobSidecarsByBlockNumHandlerFunc) Handle(params GetBSCBlobSidecarsByBlockNumParams) middleware.Responder {
	return fn(params)
}

// GetBSCBlobSidecarsByBlockNumHandler interface for that can handle valid get b s c blob sidecars by block num params
type GetBSCBlobSidecarsByBlockNumHandler interface {
	Handle(GetBSCBlobSidecarsByBlockNumParams) middleware.Responder
}

// NewGetBSCBlobSidecarsByBlockNum creates a new http.Handler for the get b s c blob sidecars by block num operation
func NewGetBSCBlobSidecarsByBlockNum(ctx *middleware.Context, handler GetBSCBlobSidecarsByBlockNumHandler) *GetBSCBlobSidecarsByBlockNum {
	return &GetBSCBlobSidecarsByBlockNum{Context: ctx, Handler: handler}
}

/*
	GetBSCBlobSidecarsByBlockNum swagger:route POST / blob getBSCBlobSidecarsByBlockNum

Get BSC blob sidecars by block num
*/
type GetBSCBlobSidecarsByBlockNum struct {
	Context *middleware.Context
	Handler GetBSCBlobSidecarsByBlockNumHandler
}

func (o *GetBSCBlobSidecarsByBlockNum) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBSCBlobSidecarsByBlockNumParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
