// Code generated by go-swagger; DO NOT EDIT.

package blob

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetBlobSidecarsByBlockNumURL generates an URL for the get blob sidecars by block num operation
type GetBlobSidecarsByBlockNumURL struct {
	BlockID string

	Indices []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetBlobSidecarsByBlockNumURL) WithBasePath(bp string) *GetBlobSidecarsByBlockNumURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetBlobSidecarsByBlockNumURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetBlobSidecarsByBlockNumURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/eth/v1/beacon/blob_sidecars/{block_id}"

	blockID := o.BlockID
	if blockID != "" {
		_path = strings.Replace(_path, "{block_id}", blockID, -1)
	} else {
		return nil, errors.New("blockId is required on GetBlobSidecarsByBlockNumURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var indicesIR []string
	for _, indicesI := range o.Indices {
		indicesIS := indicesI
		if indicesIS != "" {
			indicesIR = append(indicesIR, indicesIS)
		}
	}

	indices := swag.JoinByFormat(indicesIR, "")

	if len(indices) > 0 {
		qsv := indices[0]
		if qsv != "" {
			qs.Set("indices", qsv)
		}
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetBlobSidecarsByBlockNumURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetBlobSidecarsByBlockNumURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetBlobSidecarsByBlockNumURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetBlobSidecarsByBlockNumURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetBlobSidecarsByBlockNumURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetBlobSidecarsByBlockNumURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
