// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetBlobSideCarsResponse get blob side cars response
//
// swagger:model GetBlobSideCarsResponse
type GetBlobSideCarsResponse struct {

	// code defined by api,not equal to http code
	// Example: 2000
	Code int64 `json:"code,omitempty"`

	// data
	Data *GetBlobSideCarsResponseData `json:"data,omitempty"`

	// error message if there is error
	// Example: signature invalid
	Message string `json:"message,omitempty"`
}

// Validate validates this get blob side cars response
func (m *GetBlobSideCarsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetBlobSideCarsResponse) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get blob side cars response based on the context it is used
func (m *GetBlobSideCarsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetBlobSideCarsResponse) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if m.Data != nil {
		if err := m.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetBlobSideCarsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetBlobSideCarsResponse) UnmarshalBinary(b []byte) error {
	var res GetBlobSideCarsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// GetBlobSideCarsResponseData actual data for request
//
// swagger:model GetBlobSideCarsResponseData
type GetBlobSideCarsResponseData struct {

	// sidecar
	Sidecar []*Sidecar `json:"sidecar"`
}

// Validate validates this get blob side cars response data
func (m *GetBlobSideCarsResponseData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSidecar(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetBlobSideCarsResponseData) validateSidecar(formats strfmt.Registry) error {
	if swag.IsZero(m.Sidecar) { // not required
		return nil
	}

	for i := 0; i < len(m.Sidecar); i++ {
		if swag.IsZero(m.Sidecar[i]) { // not required
			continue
		}

		if m.Sidecar[i] != nil {
			if err := m.Sidecar[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data" + "." + "sidecar" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("data" + "." + "sidecar" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get blob side cars response data based on the context it is used
func (m *GetBlobSideCarsResponseData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSidecar(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetBlobSideCarsResponseData) contextValidateSidecar(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Sidecar); i++ {

		if m.Sidecar[i] != nil {
			if err := m.Sidecar[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data" + "." + "sidecar" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("data" + "." + "sidecar" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetBlobSideCarsResponseData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetBlobSideCarsResponseData) UnmarshalBinary(b []byte) error {
	var res GetBlobSideCarsResponseData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
