// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Sidecar sidecar
//
// swagger:model Sidecar
type Sidecar struct {

	// name
	// Example: Art
	Blob string `json:"blob,omitempty"`

	// index
	// Example: 1
	Index int64 `json:"index,omitempty"`
}

// Validate validates this sidecar
func (m *Sidecar) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sidecar based on context it is used
func (m *Sidecar) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Sidecar) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Sidecar) UnmarshalBinary(b []byte) error {
	var res Sidecar
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
